#!/usr/bin/env python3
# docs/pages/gen_html.py
# VERSION: 2.8.0
# Auto-generated by gendoc-gen-html — DO NOT EDIT MANUALLY

import os, re, json, html as _html
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent
DOCS_DIR = BASE / "docs"
PAGES_DIR = BASE / "docs" / "pages"
FEATURES_DIR = BASE / "features"
REQ_DIR = BASE / "docs" / "req"

def read_state():
    try:
        state_files = list(BASE.glob(".gendoc-state-*.json"))
        if state_files:
            return json.loads(state_files[0].read_text())
        return json.loads((BASE / ".gendoc-state.json").read_text())
    except:
        return {}

state = read_state()
APP_NAME = state.get("project_name") or BASE.name
GITHUB_REPO = state.get("github_repo", "")
if not GITHUB_REPO:
    try:
        import subprocess
        _url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            cwd=str(BASE), stderr=subprocess.DEVNULL
        ).decode().strip()
        GITHUB_REPO = _url.removesuffix(".git") if _url.endswith(".git") else _url
    except:
        pass

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>__TITLE__ — __APP__</title>
  <link rel="stylesheet" href="assets/style.css">
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
</head>
<body>
<nav class="top-nav">
  <a class="nav-brand" href="index.html">__APP__</a>
  <div class="nav-controls">
    <button class="sidebar-toggle" id="sidebarToggle" title="Toggle sidebar">&#9776;</button>
    __GITHUB_LINK__
    <div class="search-wrap">
      <input class="search-input" type="search" placeholder="搜尋文件…" autocomplete="off">
      <div class="search-results"></div>
    </div>
  </div>
</nav>
<div class="doc-page-banner">
  <div class="banner-breadcrumb"><a href="index.html">__APP__</a> › __TITLE__</div>
  <h1 class="banner-title">__TITLE__</h1>
  __BANNER_DESC__
</div>
<div class="page-wrapper">
  <nav class="sidebar">__SIDEBAR__</nav>
  <div class="sidebar-resizer" id="sidebarResizer"></div>
  <main class="doc-content">__CONTENT__</main>
</div>
<script>mermaid.initialize({startOnLoad:true,theme:'default'});</script>
<script src="assets/app.js"></script>
</body>
</html>"""

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>__APP__ — 文件中心</title>
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
<nav class="top-nav">
  <a class="nav-brand" href="index.html">__APP__</a>
  <div class="nav-controls">
    <button class="sidebar-toggle" id="sidebarToggle" title="Toggle sidebar">&#9776;</button>
    __GITHUB_LINK__
    <div class="search-wrap">
      <input class="search-input" type="search" placeholder="搜尋文件…" autocomplete="off">
      <div class="search-results"></div>
    </div>
  </div>
</nav>
<div class="doc-page-banner">
  <div class="banner-breadcrumb">__APP__</div>
  <h1 class="banner-title">文件中心</h1>
  <p class="banner-desc">__APP__ 全專案文件索引</p>
</div>
<div class="page-wrapper">
  <nav class="sidebar">__SIDEBAR__</nav>
  <div class="sidebar-resizer" id="sidebarResizer"></div>
  <main class="doc-content">
    <h1>文件總覽</h1>
    <div class="index-grid">__CARDS__</div>
  </main>
</div>
<script src="assets/app.js"></script>
</body>
</html>"""

DOC_PAGES = [
    ("IDEA.md",        "idea.html",         "💡", "產品創意",          "問題定義與初始概念"),
    ("BRD.md",         "brd.html",          "📋", "業務需求文件",       "Business Requirements"),
    ("PRD.md",         "prd.html",          "📝", "產品需求文件",       "User Stories & AC"),
    ("EDD.md",         "edd.html",          "⚙️",  "工程設計文件",       "Technical Architecture"),
    ("ARCH.md",        "arch.html",         "🏗️",  "架構設計",           "System Architecture"),
    ("API.md",         "api.html",          "🔌", "API 設計",           "REST & WebSocket API"),
    ("SCHEMA.md",      "schema.html",       "🗄️",  "資料庫 Schema",      "Database Design"),
    ("test-plan.md",   "test-plan.html",    "🧪", "測試計劃",           "Test Strategy & RTM"),
    ("RTM.md",         "rtm.html",          "🔗", "需求追溯矩陣",       "Requirements Traceability"),
    ("RUNBOOK.md",     "runbook.html",      "📖", "運維手冊",           "Operations Runbook"),
    ("LOCAL_DEPLOY.md","local_deploy.html", "🚀", "本地部署指南",       "Local K8s Deployment"),
    ("ALIGN_REPORT.md","align_report.html", "🔍", "對齊掃描報告",       "Alignment Check Report"),
]

SIDEBAR_LINKS = [
    ("index.html",         "🏠 首頁"),
    ("idea.html",          "💡 產品創意"),
    ("brd.html",           "📋 業務需求"),
    ("prd.html",           "📝 產品需求"),
    ("edd.html",           "⚙️  工程設計"),
    ("arch.html",          "🏗️  架構設計"),
    ("api.html",           "🔌 API 設計"),
    ("schema.html",        "🗄️  資料庫"),
    ("test-plan.html",     "🧪 測試計劃"),
    ("rtm.html",           "🔗 追溯矩陣"),
    ("runbook.html",       "📖 運維手冊"),
    ("local_deploy.html",  "🚀 本地部署"),
    ("align_report.html",  "🔍 對齊報告"),
]

def build_sidebar():
    items = []
    items.append('<div class="sidebar__section"><div class="sidebar__label">文件導覽</div>')
    for href, label in SIDEBAR_LINKS:
        items.append(f'<a class="sidebar__link" href="{href}">{label}</a>')
    items.append('</div>')
    return "\n".join(items)

def github_link():
    if not GITHUB_REPO:
        return ""
    return (f'<a class="nav-gh-link" href="{GITHUB_REPO}" target="_blank" rel="noopener">'
            f'<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">'
            f'<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>'
            f'</svg> GitHub</a>')

def md_to_html(md_text):
    text = md_text

    # Mermaid code blocks → diagram-container
    def replace_mermaid(m):
        code = _html.escape(m.group(1).strip())
        return (f'<div class="diagram-container" title="點擊放大">'
                f'<div class="mermaid">{code}</div></div>')
    text = re.sub(r'```mermaid\s*\n(.*?)```', replace_mermaid, text, flags=re.DOTALL)

    # Fenced code blocks
    def replace_code(m):
        lang = _html.escape(m.group(1).strip()) if m.group(1) else ""
        code = _html.escape(m.group(2))
        cls = f' class="language-{lang}"' if lang else ""
        return f'<pre><code{cls}>{code}</code></pre>'
    text = re.sub(r'```(\w*)\n?(.*?)```', replace_code, text, flags=re.DOTALL)

    # Inline code
    text = re.sub(r'`([^`]+)`', lambda m: f'<code>{_html.escape(m.group(1))}</code>', text)

    # Headers
    for level in range(6, 0, -1):
        hashes = '#' * level
        text = re.sub(
            rf'^{hashes} (.+)$',
            lambda m, l=level: f'<h{l} id="{re.sub(chr(32), "-", m.group(1).lower())}">{m.group(1)}</h{l}>',
            text, flags=re.MULTILINE
        )

    # Bold / Italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)

    # Horizontal rule
    text = re.sub(r'^---+\s*$', '<hr>', text, flags=re.MULTILINE)

    # Blockquotes
    def replace_blockquote(m):
        inner = re.sub(r'^> ?', '', m.group(0), flags=re.MULTILINE)
        return f'<blockquote>{inner.strip()}</blockquote>'
    text = re.sub(r'(^> .+\n?)+', replace_blockquote, text, flags=re.MULTILINE)

    # Tables
    def replace_table(m):
        rows = [r.strip() for r in m.group(0).strip().splitlines() if r.strip()]
        html_rows = []
        for i, row in enumerate(rows):
            if re.match(r'^\|[-| :]+\|$', row):
                continue
            cells = [c.strip() for c in row.strip('|').split('|')]
            tag = 'th' if i == 0 else 'td'
            html_rows.append('<tr>' + ''.join(f'<{tag}>{c}</{tag}>' for c in cells) + '</tr>')
        return '<table>' + ''.join(html_rows) + '</table>'
    text = re.sub(r'(\|.+\|\n)+', replace_table, text)

    # Unordered lists
    def replace_ul(m):
        items = re.findall(r'^[-*+] (.+)$', m.group(0), re.MULTILINE)
        return '<ul>' + ''.join(f'<li>{i}</li>' for i in items) + '</ul>'
    text = re.sub(r'(^[-*+] .+\n?)+', replace_ul, text, flags=re.MULTILINE)

    # Ordered lists
    def replace_ol(m):
        items = re.findall(r'^\d+\. (.+)$', m.group(0), re.MULTILINE)
        return '<ol>' + ''.join(f'<li>{i}</li>' for i in items) + '</ol>'
    text = re.sub(r'(^\d+\. .+\n?)+', replace_ol, text, flags=re.MULTILINE)

    # Links
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)

    # Images → badges or img
    text = re.sub(
        r'!\[([^\]]*)\]\(([^)]+)\)',
        lambda m: (f'<img src="{m.group(2)}" alt="{_html.escape(m.group(1))}" '
                   f'onerror="this.replaceWith(Object.assign(document.createElement(\'span\'),'
                   f'{{className:\'badge-fallback\',textContent:\'{_html.escape(m.group(1))}\'}}))" loading="lazy">'
                   if m.group(2).startswith('http')
                   else f'<span class="badge-fallback">{_html.escape(m.group(1))}</span>'),
        text
    )

    # Paragraphs — wrap bare text lines
    lines = text.split('\n')
    result = []
    in_block = False
    block_tags = {'<h','<ul','<ol','<li','<table','<blockquote','<pre','<hr','<div','<img'}
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_block:
                result.append('</p>')
                in_block = False
            continue
        if any(stripped.startswith(t) for t in block_tags):
            if in_block:
                result.append('</p>')
                in_block = False
            result.append(stripped)
        else:
            if not in_block:
                result.append('<p>')
                in_block = True
            result.append(stripped)
    if in_block:
        result.append('</p>')
    return '\n'.join(result)

def build_search_data():
    data = {}
    for md_file, html_file, icon, title, desc in DOC_PAGES:
        md_path = DOCS_DIR / md_file
        if not md_path.exists():
            continue
        content = md_path.read_text(encoding='utf-8', errors='replace')
        # Strip markdown syntax for excerpt
        plain = re.sub(r'[#*`>|\[\]!]', ' ', content)
        plain = re.sub(r'\s+', ' ', plain).strip()
        data[html_file] = {
            "title": title,
            "url": html_file,
            "excerpt": plain[:300],
        }
    return data

def generate_page(md_file, html_file, title, desc):
    md_path = DOCS_DIR / md_file
    if not md_path.exists():
        print(f"  [SKIP] {md_file} not found")
        return False

    content_md = md_path.read_text(encoding='utf-8', errors='replace')
    content_html = md_to_html(content_md)
    sidebar = build_sidebar()
    gh = github_link()
    banner_desc = f'<p class="banner-desc">{desc}</p>' if desc else ''

    page = (HTML_TEMPLATE
            .replace('__APP__', _html.escape(APP_NAME))
            .replace('__TITLE__', _html.escape(title))
            .replace('__GITHUB_LINK__', gh)
            .replace('__BANNER_DESC__', banner_desc)
            .replace('__SIDEBAR__', sidebar)
            .replace('__CONTENT__', content_html))

    out_path = PAGES_DIR / html_file
    out_path.write_text(page, encoding='utf-8')
    print(f"  [OK] {html_file} ({len(page):,} bytes)")
    return True

def generate_index():
    sidebar = build_sidebar()
    gh = github_link()

    cards = []
    for md_file, html_file, icon, title, desc in DOC_PAGES:
        md_path = DOCS_DIR / md_file
        if not md_path.exists():
            continue
        cards.append(
            f'<a class="index-card" href="{html_file}">'
            f'<span class="index-card__icon">{icon}</span>'
            f'<span class="index-card__title">{_html.escape(title)}</span>'
            f'<span class="index-card__desc">{_html.escape(desc)}</span>'
            f'</a>'
        )

    page = (INDEX_TEMPLATE
            .replace('__APP__', _html.escape(APP_NAME))
            .replace('__GITHUB_LINK__', gh)
            .replace('__SIDEBAR__', sidebar)
            .replace('__CARDS__', '\n'.join(cards)))

    out_path = PAGES_DIR / "index.html"
    out_path.write_text(page, encoding='utf-8')
    print(f"  [OK] index.html ({len(page):,} bytes)")

def main():
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    (PAGES_DIR / "assets").mkdir(exist_ok=True)

    print(f"=== gendoc-gen-html v2.8.0 ===")
    print(f"Project : {APP_NAME}")
    print(f"Source  : {DOCS_DIR}")
    print(f"Output  : {PAGES_DIR}")
    print()

    # Index
    generate_index()

    # Doc pages
    generated = 0
    for md_file, html_file, icon, title, desc in DOC_PAGES:
        if generate_page(md_file, html_file, title, desc):
            generated += 1

    # Search data
    search_data = build_search_data()
    search_path = PAGES_DIR / "search-data.json"
    search_path.write_text(json.dumps(search_data, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f"  [OK] search-data.json ({len(search_data)} entries)")

    print()
    print(f"=== Done: index.html + {generated} doc pages + search-data.json ===")

if __name__ == "__main__":
    main()
