// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 OrderDTO / docs/SCHEMA.md §3.6
// Stereotype: <<AggregateRoot>>

export type OrderType = 'DIAMOND_PACK' | 'VIP_SUBSCRIPTION' | 'WEAPON_PACK';
export type OrderStatus = 'PENDING' | 'COMPLETED' | 'FAILED' | 'REFUNDED';
export type OrderPlatform = 'apple' | 'google';

export class Order {
  // TODO: Implement — extracted from SCHEMA.md §3.6 + EDD.md §10.6 OrderDTO
  private readonly id: string;           // UUID v4 (冪等 key)
  private readonly userId: string;        // CUID2
  private readonly productId: string;
  private readonly orderType: OrderType;
  private readonly amountUsd: number;     // Decimal(10,2)
  private status: OrderStatus;
  private diamondsCredited: number;       // >= 0
  private transactionId: string | null;
  private receiptHash: string | null;     // SHA-256(receipt)
  private readonly idempotencyKey: string; // UUID v4
  private readonly createdAt: Date;
  private completedAt: Date | null;

  private constructor(params: {
    id: string;
    userId: string;
    productId: string;
    orderType: OrderType;
    amountUsd: number;
    idempotencyKey: string;
  }) {
    // TODO: implement constructor
    this.id = params.id;
    this.userId = params.userId;
    this.productId = params.productId;
    this.orderType = params.orderType;
    this.amountUsd = params.amountUsd;
    this.status = 'PENDING';
    this.diamondsCredited = 0;
    this.transactionId = null;
    this.receiptHash = null;
    this.idempotencyKey = params.idempotencyKey;
    this.createdAt = new Date();
    this.completedAt = null;
  }

  static create(params: {
    id: string;
    userId: string;
    productId: string;
    orderType: OrderType;
    amountUsd: number;
    idempotencyKey: string;
  }): Order {
    // TODO: implement — validate idempotencyKey is UUID v4
    // See EDD.md §1.3 US-SHOP-001 AC-1: order_id 冪等保證
    throw new Error('Not implemented');
  }

  complete(params: {
    transactionId: string;
    receiptHash: string;
    diamondsCredited: number;
  }): void {
    // TODO: implement — validate status is PENDING, set to COMPLETED
    throw new Error('Not implemented');
  }

  fail(): void {
    // TODO: implement — set status to FAILED
    throw new Error('Not implemented');
  }

  // Getters
  getId(): string { return this.id; }
  getUserId(): string { return this.userId; }
  getStatus(): OrderStatus { return this.status; }
  getIdempotencyKey(): string { return this.idempotencyKey; }
}
