// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 IShopService interface
// Stereotype: <<ApplicationService>>

import { OrderDTO } from '../../domain/commerce/OrderDTO';
import { ProductDTO } from '../../domain/commerce/ProductDTO';
import { VipSubscriptionDTO } from '../../domain/account/VipSubscriptionDTO';

export interface PaginatedResult<T> {
  items: T[];
  total: number;
  page: number;
  limit: number;
  has_next: boolean;
}

export interface IShopService {
  /** 查詢所有上架商品列表 */
  listProducts(): Promise<ProductDTO[]>;

  /** 建立訂單（含 order_id 冪等保證）；order_id 由客戶端生成（UUID v4）*/
  createOrder(userId: string, productId: string, orderId: string): Promise<OrderDTO>;

  /**
   * 驗證 IAP Receipt 並發放鑽石；冪等（相同 order_id 多次呼叫返回同一結果）
   * See EDD.md §10.9 Activity Diagram 購買流程
   */
  verifyIAPReceipt(
    orderId: string,
    iapReceipt: string,
    platform: 'apple' | 'google'
  ): Promise<OrderDTO>;

  /** 查詢用戶訂單列表（分頁）*/
  listOrders(userId: string, page: number, limit: number): Promise<PaginatedResult<OrderDTO>>;

  /** 查詢單一訂單狀態 */
  getOrderById(orderId: string): Promise<OrderDTO>;

  /**
   * 訂閱 VIP；建立 VipSubscription 記錄並發佈 VipActivated 事件
   * 需帶 idempotency key，防重複扣鑽
   */
  subscribeVip(
    userId: string,
    planId: string,
    idempotencyKey: string
  ): Promise<VipSubscriptionDTO>;
}
