// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 / docs/SCHEMA.md §3.1
// Stereotype: <<AggregateRoot>>

export type UserRole = 'player' | 'operator' | 'superadmin';
export type UserStatus = 'active' | 'suspended' | 'banned';
export type AgeStatus = 'UNVERIFIED' | 'DEMO_ONLY' | 'VERIFIED';

export class User {
  // TODO: Implement — extracted from SCHEMA.md §3.1 + EDD.md §10.6
  private readonly id: string;         // CUID2 (前綴 usr_)
  private emailMasked: string;         // PII — 遮罩後回傳
  private displayName: string;         // 2–30 字元
  private role: UserRole;
  private status: UserStatus;
  private ageStatus: AgeStatus;
  private vipTier: number;             // 0–3
  private vipExpiresAt: Date | null;
  private goldBalance: bigint;         // coin，非負
  private diamondBalance: number;      // 非負整數
  private failedLoginCount: number;    // 0–255
  private lockedAt: Date | null;
  private readonly createdAt: Date;

  private constructor(params: {
    id: string;
    emailMasked: string;
    displayName: string;
    role: UserRole;
    status: UserStatus;
    ageStatus: AgeStatus;
    vipTier: number;
    vipExpiresAt: Date | null;
    goldBalance: bigint;
    diamondBalance: number;
    createdAt: Date;
  }) {
    // TODO: implement constructor validation
    // See SCHEMA.md §9.2 CHECK constraints: gold_balance >= 0, diamond_balance >= 0, vip_tier 0-3
    this.id = params.id;
    this.emailMasked = params.emailMasked;
    this.displayName = params.displayName;
    this.role = params.role;
    this.status = params.status;
    this.ageStatus = params.ageStatus;
    this.vipTier = params.vipTier;
    this.vipExpiresAt = params.vipExpiresAt;
    this.goldBalance = params.goldBalance;
    this.diamondBalance = params.diamondBalance;
    this.failedLoginCount = 0;
    this.lockedAt = null;
    this.createdAt = params.createdAt;
  }

  static create(params: {
    id: string;
    email: string;
    displayName: string;
    birthdate: Date;
  }): User {
    // TODO: implement — validate age >= 18, set ageStatus
    // See EDD.md §1.3 US-AGE-001 AC-1, AC-2
    throw new Error('Not implemented');
  }

  static reconstitute(params: {
    id: string;
    emailMasked: string;
    displayName: string;
    role: UserRole;
    status: UserStatus;
    ageStatus: AgeStatus;
    vipTier: number;
    vipExpiresAt: Date | null;
    goldBalance: bigint;
    diamondBalance: number;
    failedLoginCount: number;
    lockedAt: Date | null;
    createdAt: Date;
  }): User {
    // TODO: implement reconstitution from persistence
    throw new Error('Not implemented');
  }

  recordLoginFailure(): void {
    // TODO: implement — increment failedLoginCount, lock if >= 5
    // See EDD.md §1.3 US-ACCT-001 AC-3: 5 failures → lock 15 min
    throw new Error('Not implemented');
  }

  resetLoginFailures(): void {
    // TODO: implement
    throw new Error('Not implemented');
  }

  suspend(reason: string): void {
    // TODO: implement — set status = 'suspended'
    throw new Error('Not implemented');
  }

  ban(reason: string): void {
    // TODO: implement — set status = 'banned'
    throw new Error('Not implemented');
  }

  activate(): void {
    // TODO: implement — set status = 'active'
    throw new Error('Not implemented');
  }

  creditGold(amount: bigint): void {
    // TODO: implement — validate amount >= 0, add to goldBalance
    throw new Error('Not implemented');
  }

  debitGold(amount: bigint): void {
    // TODO: implement — validate goldBalance >= amount before deducting
    throw new Error('Not implemented');
  }

  // Getters
  getId(): string { return this.id; }
  getEmailMasked(): string { return this.emailMasked; }
  getDisplayName(): string { return this.displayName; }
  getRole(): UserRole { return this.role; }
  getStatus(): UserStatus { return this.status; }
  getAgeStatus(): AgeStatus { return this.ageStatus; }
  getVipTier(): number { return this.vipTier; }
  getGoldBalance(): bigint { return this.goldBalance; }
  getDiamondBalance(): number { return this.diamondBalance; }
  isLocked(): boolean { return this.lockedAt !== null; }
}
