// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 IAccountService interface
// Stereotype: <<ApplicationService>>

import { UserDTO } from '../../domain/account/UserDTO';
import { AuthTokenPairDTO } from '../../domain/account/AuthTokenPairDTO';
import { BalanceDTO } from '../../domain/account/BalanceDTO';
import { VipSubscriptionDTO } from '../../domain/account/VipSubscriptionDTO';

export interface IAccountService {
  /** 玩家註冊；email 唯一；birthdate 用於年齡驗證（需 >= 18 歲） */
  register(email: string, password: string, displayName: string, birthdate: Date): Promise<UserDTO>;

  /** 登入驗證；成功回傳 JWT Access（15min）+ Refresh Token（7d）組合 */
  login(email: string, password: string): Promise<AuthTokenPairDTO>;

  /** 使用 Refresh Token 換發新 Access Token */
  refreshToken(refreshToken: string): Promise<AuthTokenPairDTO>;

  /** 登出；吊銷 Refresh Token */
  logout(refreshToken: string): Promise<void>;

  /** 查詢玩家資料（需 BOLA 驗證：呼叫者需為本人或 Operator+）*/
  getUserById(userId: string): Promise<UserDTO>;

  /** 更新玩家年齡驗證狀態 */
  verifyAge(userId: string, declaredAge: number): Promise<void>;

  /** 封鎖玩家帳號（需 Operator 或 SuperAdmin 角色）*/
  banUser(userId: string, reason: string, operatorId: string): Promise<void>;

  /** 查詢玩家金幣與鑽石餘額 */
  getBalance(userId: string): Promise<BalanceDTO>;

  /** 更新金幣餘額（遊戲結算用；冪等，帶 session_id）*/
  creditGold(userId: string, amount: number, sessionId: string): Promise<BalanceDTO>;

  /** 查詢 VIP 訂閱狀態 */
  getVipStatus(userId: string): Promise<VipSubscriptionDTO | null>;
}
