// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 Class Diagram
// Stereotype: <<Entity>>

import { Fish } from './Fish';

export interface ConsolationReward {
  userId: string;
  coins: number;
}

export class BossFish extends Fish {
  readonly escapeTimeout: number;    // milliseconds before boss escapes
  readonly consolationRate: number;  // consolation payout ratio when boss escapes

  constructor(params: {
    id: string;
    baseValue: number;
    hitPoints: number;
    escapeTimeout: number;
    consolationRate: number;
  }) {
    super({ ...params, type: 'BOSS' });
    this.escapeTimeout = params.escapeTimeout;
    this.consolationRate = params.consolationRate;
  }

  onEscape(): ConsolationReward[] {
    // TODO: implement — calculate consolation rewards for all players in session
    // See EDD.md §10.6 BossFish.onEscape() — consolationRate applies to baseValue
    throw new Error('Not implemented');
  }
}
