// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 Class Diagram
// Stereotype: <<Entity>>

export type FishType = 'NORMAL' | 'ELITE' | 'BOSS' | 'JACKPOT_FISH';

export class Fish {
  // TODO: Implement — extracted from Class Diagram
  readonly id: string;
  readonly type: FishType;
  readonly baseValue: number;
  private hitPoints: number;

  constructor(params: {
    id: string;
    type: FishType;
    baseValue: number;
    hitPoints: number;
  }) {
    this.id = params.id;
    this.type = params.type;
    this.baseValue = params.baseValue;
    this.hitPoints = params.hitPoints;
  }

  isAlive(): boolean {
    // TODO: implement
    throw new Error('Not implemented');
  }

  takeDamage(dmg: number): void {
    // TODO: implement — apply damage and update hitPoints
    throw new Error('Not implemented');
  }

  getHitPoints(): number {
    return this.hitPoints;
  }
}
