// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 Class Diagram
// Stereotype: <<interface>>

export interface HitResult {
  isHit: boolean;
  coinsAwarded: number;
  rtpAfter: number;
}

export interface RTPState {
  userId: string;
  currentRtp: number;
  sessionCoinsIn: number;
  sessionCoinsOut: number;
}

export interface Weapon {
  type: string;
  damage: number;
}

/**
 * RTP Engine interface — Server-Authoritative hit calculation.
 * Implementations: DefaultRTPEngine (Redis-backed), DegradedRTPEngine (fixed rate).
 * See EDD.md §7 RTP Engine / ADR-003
 */
export interface IRTPEngine {
  calculateHit(userId: string, fishId: string, weapon: Weapon): Promise<HitResult>;
  getRTPState(userId: string): Promise<RTPState>;
}
