// Generated by gendoc-gen-contracts | Source: docs/EDD.md §10.6 Class Diagram + §10.8 Communication Diagram
// Stereotype: <<DomainService>>

export interface JackpotResult {
  triggered: boolean;
  winnerId?: string;
  amount?: number;
}

export class JackpotService {
  // TODO: Implement — extracted from Class Diagram
  private redis: unknown; // inject Redis client

  constructor(redis: unknown) {
    this.redis = redis;
  }

  /**
   * Contribute to jackpot pool.
   * Called on each fish kill (5 coin contribution per kill — see EDD.md §10.2).
   */
  async contribute(sessionId: string, amount: number): Promise<void> {
    // TODO: implement — INCR jackpot_pool:{sessionId} in Redis
    // See EDD.md §10.2 Sequence: Room->>Redis: INCR jackpot_pool (by 5)
    throw new Error('Not implemented');
  }

  /**
   * Check jackpot trigger condition and trigger atomically via Lua Script.
   * Uses Redis EVALSHA (SETNX jackpot_lock) to ensure uniqueness.
   * See EDD.md §10.8 Communication Diagram
   */
  async checkAndTrigger(sessionId: string, userId?: string): Promise<JackpotResult> {
    // TODO: implement — Redis Lua Script atomic jackpot trigger
    // EVALSHA lua_jackpot_lock (SETNX jackpot_lock)
    // GET jackpot_pool_amount → trigger if > jackpot_min_pool
    // SET jackpot_pool_amount 1000 (reset to seed value)
    throw new Error('Not implemented');
  }
}
