// Generated by gendoc-gen-contracts | Source: docs/EDD.md §3.1 Architecture + Repository Pattern
// Stereotype: <<Repository>>

import { Order } from '../../domain/commerce/Order';

export interface IOrderRepository {
  findById(id: string): Promise<Order | null>;
  findByIdempotencyKey(key: string): Promise<Order | null>;
  findByUserId(userId: string, page: number, limit: number): Promise<{ items: Order[]; total: number }>;
  save(order: Order): Promise<void>;
  update(order: Order): Promise<void>;
}
