// Generated by gendoc-gen-contracts | Source: docs/EDD.md §3.1 Architecture + Repository Pattern
// Stereotype: <<Repository>>

import { User } from '../../domain/account/User';

export interface IUserRepository {
  findById(id: string): Promise<User | null>;
  findByEmail(email: string): Promise<User | null>;
  save(user: User): Promise<void>;
  update(user: User): Promise<void>;
  softDelete(id: string): Promise<void>;
}
